package com.c1se_01.roomiego.dto;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class SendMessageRequestTest {

  @Test
  public void testGetNumericConversationId_NullConversationId() {
    SendMessageRequest request = new SendMessageRequest();
    request.setConversationId(null);
    assertNull(request.getNumericConversationId());
  }

  @Test
  public void testGetNumericConversationId_DoesNotStartWithConv() {
    SendMessageRequest request = new SendMessageRequest();
    request.setConversationId("chat_123");
    assertNull(request.getNumericConversationId());
  }

  @Test
  public void testGetNumericConversationId_StartsWithConvNoUnderscore() {
    SendMessageRequest request = new SendMessageRequest();
    request.setConversationId("conv123");
    assertNull(request.getNumericConversationId());
  }

  @Test
  public void testGetNumericConversationId_StartsWithConvSingleUnderscoreNoNumber() {
    SendMessageRequest request = new SendMessageRequest();
    request.setConversationId("conv_");
    assertNull(request.getNumericConversationId());
  }

  @Test
  public void testGetNumericConversationId_StartsWithConvSingleUnderscoreWithNumber() {
    SendMessageRequest request = new SendMessageRequest();
    request.setConversationId("conv_123");
    assertEquals(123L, request.getNumericConversationId());
  }

  @Test
  public void testGetNumericConversationId_StartsWithConvMultipleUnderscoresLastIsNumber() {
    SendMessageRequest request = new SendMessageRequest();
    request.setConversationId("conv_abc_456");
    assertEquals(456L, request.getNumericConversationId());
  }

  @Test
  public void testGetNumericConversationId_StartsWithConvMultipleUnderscoresLastIsNotNumber() {
    SendMessageRequest request = new SendMessageRequest();
    request.setConversationId("conv_123_abc");
    assertNull(request.getNumericConversationId());
  }

  @Test
  public void testGetNumericConversationId_StartsWithConvTrailingUnderscore() {
    SendMessageRequest request = new SendMessageRequest();
    request.setConversationId("conv_123_");
    assertEquals(123L, request.getNumericConversationId());
  }

  @Test
  public void testGetNumericConversationId_StartsWithConvLargeNumber() {
    SendMessageRequest request = new SendMessageRequest();
    request.setConversationId("conv_999999999999999");
    assertEquals(999999999999999L, request.getNumericConversationId());
  }

  @Test
  public void testGetNumericConversationId_StartsWithConvZero() {
    SendMessageRequest request = new SendMessageRequest();
    request.setConversationId("conv_0");
    assertEquals(0L, request.getNumericConversationId());
  }

  @Test
  public void testGetNumericConversationId_StartsWithConvNegativeNumber() {
    SendMessageRequest request = new SendMessageRequest();
    request.setConversationId("conv_-123");
    assertEquals(-123L, request.getNumericConversationId());
  }

  // Test getters and setters for completeness, though generated by Lombok
  @Test
  public void testSettersAndGetters() {
    SendMessageRequest request = new SendMessageRequest();
    request.setConversationId("conv_789");
    request.setSenderId(456L);
    request.setContent("Hello World");

    assertEquals("conv_789", request.getConversationId());
    assertEquals(456L, request.getSenderId());
    assertEquals("Hello World", request.getContent());
  }
}